### ISSUE TITLE
Efficiency, where to store session

### ISSUE THREAD

**Issue by aronca** [moustakas/legacyhalos-web#6]
Currently in order to store the search results to a session, we serialize our queryset of objects using JSON then store to a session variable, which we configured to use the database, over cache or other options.
Setting session variable:
https://github.com/moustakas/legacyhalos-web/blob/9bcbdc96826ba03bdff07f38ee630932bc0a3ab4/legacyhalos_web/centrals/views.py#L16

Serializing:
https://github.com/moustakas/legacyhalos-web/blob/9bcbdc96826ba03bdff07f38ee630932bc0a3ab4/legacyhalos_web/centrals/views.py#L37-L41

Loading from session variable:
https://github.com/moustakas/legacyhalos-web/blob/9bcbdc96826ba03bdff07f38ee630932bc0a3ab4/legacyhalos_web/centrals/views.py#L27

Is this an efficient way to remember our query result to use it on individual central galaxy pages, in order to link to previous and next galaxy pages?
Is it better to store the session to cache, or to the database like we are currently?
Will this approach scale up once we have a larger data set?

**Comment by dstndstn** [comment]
Hi,

You definitely want to avoid running the query and storing the results in the session; you want to store the un-evaluated QuerySet in the session.  (I can't tell off-hand whether what you've got here is doing that or not.)

Rather than using JSON to serialize it, you should use "pickle", which is python's native serialization language.

There is some documentation and example code on exactly this question, here:

https://docs.djangoproject.com/en/2.0/ref/models/querysets/#pickling-querysets

Other useful reading is this, on when a QuerySet actually queries the database; basically, you only want to be querying the database for one page of results at a time, using slices:
https://docs.djangoproject.com/en/2.0/ref/models/querysets/#when-querysets-are-evaluated

Hope that helps!
